name: Tests

# bpo-40548: "paths-ignore" is not used to skip documentation-only PRs, because
# it prevents to mark a job as mandatory. A PR cannot be merged if a job is
# mandatory but not scheduled because of "paths-ignore".
on:
  push:
    branches:
    - 'main'
    - '3.10'
    - '3.9'
    - '3.8'
    - '3.7'
  pull_request:
    branches:
    - 'main'
    - '3.10'
    - '3.9'
    - '3.8'
    - '3.7'

jobs:
  build_win32:
    name: 'Windows (x86)'
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build CPython
      run: .\PCbuild\build.bat -e -p Win32
    - name: Display build info
      run: .\python.bat -m test.pythoninfo
    - name: Tests
      run: .\PCbuild\rt.bat -p Win32 -q -uall -u-cpu -rwW --slowest --timeout=1200 -j0 test_sqlite

  build_win_amd64:
    name: 'Windows (x64)'
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Register MSVC problem matcher
      run: echo "::add-matcher::.github/problem-matchers/msvc.json"
    - name: Build CPython
      run: .\PCbuild\build.bat -e -p x64
    - name: Display build info
      run: .\python.bat -m test.pythoninfo
    - name: Tests
      run: .\PCbuild\rt.bat -p x64 -q -uall -u-cpu -rwW --slowest --timeout=1200 -j0 test_sqlite
