name: Tests

# gh-84728: "paths-ignore" is not used to skip documentation-only PRs, because
# it prevents to mark a job as mandatory. A PR cannot be merged if a job is
# mandatory but not scheduled because of "paths-ignore".
on:
  workflow_dispatch:
  push:
    branches:
    - 'main'
    - '3.12'
    - '3.11'
    - '3.10'
    - '3.9'
    - '3.8'
    - '3.7'
  pull_request:
    branches:
    - 'main'
    - '3.12'
    - '3.11'
    - '3.10'
    - '3.9'
    - '3.8'
    - '3.7'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-reusable
  cancel-in-progress: true

jobs:
  build_macos:
    name: 'macOS'
    runs-on: macos-latest
    timeout-minutes: 60
    env:
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      HOMEBREW_BREW_GIT_REMOTE: 0
      HOMEBREW_NO_INSTALL_FROM_API: 1
      PYTHONSTRICTEXTENSIONBUILD: 1
    steps:
    - uses: actions/checkout@v3
    - name: Restore config.cache
      uses: actions/cache@v3
      with:
        path: config.cache
        key: ${{ github.job }}-${{ runner.os }}-${{ needs.check_source.outputs.config_hash }}
    - name: Install Homebrew dependencies
      run: brew install pkg-config openssl@3.0 xz gdbm tcl-tk
    - name: Upgrade OpenSSL to the most recent version
      run: brew upgrade -f openssl@3.0
    #- name: Configure CPython
    #  run: |
    #    GDBM_CFLAGS="-I$(brew --prefix gdbm)/include" \
    #    GDBM_LIBS="-L$(brew --prefix gdbm)/lib -lgdbm" \
    #    ./configure \
    #      --config-cache \
    #      --with-pydebug \
    #      --prefix=/opt/python-dev \
    #      --with-openssl="$(brew --prefix openssl@3.0)"
    #- name: Build CPython
    #  run: make -j4
    #- name: Display build info
    #  run: make pythoninfo
